pipeline {
    agent any

    stages {
        stage('Preparation') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building...'
                sh 'mvn clean package'
                sh 'docker build -t position-simulator:${env.BUILD_ID} .'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying to Kubernetes...'
                sh "kubectl set image deployment/position-simulator position-simulator=position-simulator:${env.BUILD_ID}"
                sh 'kubectl rollout status deployment/position-simulator'
            }
        }
    }
}
